#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_ENV_FILE="${ROOT_DIR}/.env"
SERVER_ENV_FILE="${ROOT_DIR}/apps/server/.env"
WEB_ENV_FILE="${ROOT_DIR}/apps/web/.env"

info() {
  printf '[crikket-local] %s\n' "$1"
}

warn() {
  printf '[crikket-local] warning: %s\n' "$1" >&2
}

die() {
  printf '[crikket-local] error: %s\n' "$1" >&2
  exit 1
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

generate_secret() {
  local length="${1:-48}"
  local secret=""

  if command_exists openssl; then
    secret="$(openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | cut -c1-"$length")"
  else
    secret="$(
      set +o pipefail
      LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$length"
    )"
  fi

  if [[ -z "$secret" ]]; then
    die "Failed to generate a secure random secret."
  fi

  printf '%s\n' "$secret"
}

prompt_required_value() {
  local label="$1"
  local default="${2:-}"
  local value=""

  while true; do
    if [[ -n "$default" ]]; then
      read -r -p "${label} [${default}]: " value
      value="${value:-$default}"
    else
      read -r -p "${label}: " value
    fi

    if [[ -n "$value" ]]; then
      printf '%s\n' "$value"
      return 0
    fi
    warn "${label} is required."
  done
}
get_local_ip() {
  local ip=""
  if command_exists ipconfig; then
    ip="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
  fi
  if [[ -z "$ip" ]] && command_exists hostname; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  if [[ -z "$ip" ]]; then
    ip="$(ifconfig 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n 1 || true)"
  fi
  printf '%s\n' "$ip"
}

USE_IP=false
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --ip)
      USE_IP=true
      shift
      ;;
    *)
      warn "Unknown option: $1"
      shift
      ;;
  esac
done

HOST_NAME="localhost"
if [[ "$USE_IP" == "true" ]]; then
  IP_ADDR="$(get_local_ip)"
  if [[ -n "$IP_ADDR" ]]; then
    info "Using detected IP address: ${IP_ADDR}"
    HOST_NAME="${IP_ADDR}"
  else
    warn "Could not detect local IP address. Falling back to localhost."
  fi
fi

info "Configuring Crikket local server setup..."

# 1. Ask for S3 configuration
info "Please enter your AWS S3 details (required for screenshot/recording uploads):"
STORAGE_BUCKET="$(prompt_required_value "AWS S3 Bucket Name")"
STORAGE_ACCESS_KEY_ID="$(prompt_required_value "AWS Access Key ID")"
STORAGE_SECRET_ACCESS_KEY="$(prompt_required_value "AWS Secret Access Key")"
STORAGE_REGION="$(prompt_required_value "AWS Region" "us-east-1")"

# 2. Generate secure secrets
BETTER_AUTH_SECRET="$(generate_secret 64)"
CAPTURE_SUBMIT_TOKEN_SECRET="$(generate_secret 64)"

# 3. Create root .env
info "Writing root .env file..."
cat >"$ROOT_ENV_FILE" <<EOF
# Generated by setup-local.sh
CRIKKET_PROXY_MODE=none
CRIKKET_DATABASE_MODE=bundled
WEB_PORT=7031
SERVER_PORT=7032
POSTGRES_PORT=7035

POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=crikket
POSTGRES_HOST_AUTH_METHOD=scram-sha-256
EOF

# 4. Create apps/server/.env
info "Writing apps/server/.env file..."
mkdir -p "$(dirname "$SERVER_ENV_FILE")"
cat >"$SERVER_ENV_FILE" <<EOF
NODE_ENV=production

# Database
DATABASE_URL=postgresql://postgres:postgres@postgres:5432/crikket
CORS_ORIGINS=http://${HOST_NAME}:7031
ALLOWED_SIGNUP_DOMAINS=*

# Better Auth
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
BETTER_AUTH_URL=http://${HOST_NAME}:7032
BETTER_AUTH_COOKIE_DOMAIN=${HOST_NAME}

# Payments
ENABLE_PAYMENTS=false
POLAR_ACCESS_TOKEN=
POLAR_SUCCESS_URL=
POLAR_WEBHOOK_SECRET=
POLAR_PRO_PRODUCT_ID=
POLAR_PRO_YEARLY_PRODUCT_ID=
POLAR_STUDIO_PRODUCT_ID=
POLAR_STUDIO_YEARLY_PRODUCT_ID=

# Email
RESEND_API_KEY=
RESEND_FROM_EMAIL=noreply@example.com

# AWS S3 Storage
STORAGE_BUCKET=${STORAGE_BUCKET}
STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
STORAGE_REGION=${STORAGE_REGION}
STORAGE_ENDPOINT=
STORAGE_PUBLIC_URL=

# Capture security
CAPTURE_SUBMIT_TOKEN_SECRET=${CAPTURE_SUBMIT_TOKEN_SECRET}
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=
TURNSTILE_SITE_KEY=
TURNSTILE_SECRET_KEY=
EOF

# 5. Create apps/web/.env
info "Writing apps/web/.env file..."
mkdir -p "$(dirname "$WEB_ENV_FILE")"
cat >"$WEB_ENV_FILE" <<EOF
NEXT_PUBLIC_SITE_URL=http://${HOST_NAME}:7031
NEXT_PUBLIC_APP_URL=http://${HOST_NAME}:7031
NEXT_PUBLIC_SERVER_URL=http://${HOST_NAME}:7032
NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=false

NEXT_PUBLIC_POSTHOG_KEY=
NEXT_PUBLIC_POSTHOG_HOST=
NEXT_PUBLIC_CRIKKET_KEY=
EOF

chmod 600 "$ROOT_ENV_FILE" "$SERVER_ENV_FILE" "$WEB_ENV_FILE"

info "All environment files configured successfully!"
info "You can now run: docker compose -f docker-compose.local.yml up -d"
